window:
  dimensions:
    columns: 120
    lines: 30
  decorations_theme_variant: dark
  opacity: 0.8

font:
  normal:
    family: Fira Mono
  size: 14.0

cursor:
  style:
    shape: Beam
    blinking: On

live_config_reload: true
